<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input search home</name>
   <tag></tag>
   <elementGuidId>e7832d9d-db66-4a86-af7c-e9bccfe78f17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='default-search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#default-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Cari Produk Pilihanmu&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bdde9f4d-980f-48f6-b82f-6f5eecdc3c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>default-search</value>
      <webElementGuid>aeeffb86-b6d2-40e7-be7c-b73b29f38700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full p-4 pl-10 text-sm text-gray-900 border border-[#E6E6E6] rounded-lg h-[44px]</value>
      <webElementGuid>4e76a78d-f82e-44fc-a22c-7e96dc32e24a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari Produk Pilihanmu</value>
      <webElementGuid>b6d61396-af74-4a10-9598-6f7421827600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>80aef798-adca-45e9-b987-e42fd413e563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;default-search&quot;)</value>
      <webElementGuid>95be63d3-979b-4788-b27f-7f4c4e0042dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='default-search']</value>
      <webElementGuid>0088ddea-4c8a-416c-bafa-68cabfca7429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b81976e0-87cd-4f4c-a75e-03521d0c53fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'default-search' and @placeholder = 'Cari Produk Pilihanmu' and @type = 'search']</value>
      <webElementGuid>de8640b4-e07c-4ddd-a6e4-c73056c14584</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
