<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>meal kategori</name>
   <tag></tag>
   <elementGuidId>64b7eec8-af83-4265-998d-e8d5f5f1f971</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Meal Drink$/ >> img >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4d56dfa5-4d1c-479c-9933-fddb2aee9b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>81079243-733d-4a9e-91a3-9958df34000b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d509e283-b39e-4289-ae6e-f542135d3990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2cc8cf37-4e43-4137-89a1-b68c36f66349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>6c61be2f-5124-45a3-8ada-6f38c78f905b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6b0a4763-cbf8-4ce5-8af0-f57c28e9707c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>100vw</value>
      <webElementGuid>79a09f83-09db-4296-b9f2-87a80b4c249e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=https%3A%2F%2Fsandbox-api.stagingapps.net%2Fimages%2Fcategory%2F011223-134706_category_image-1.png&amp;w=640&amp;q=75 640w, /_next/image?url=https%3A%2F%2Fsandbox-api.stagingapps.net%2Fimages%2Fcategory%2F011223-134706_category_image-1.png&amp;w=750&amp;q=75 750w, /_next/image?url=https%3A%2F%2Fsandbox-api.stagingapps.net%2Fimages%2Fcategory%2F011223-134706_category_image-1.png&amp;w=828&amp;q=75 828w, /_next/image?url=https%3A%2F%2Fsandbox-api.stagingapps.net%2Fimages%2Fcategory%2F011223-134706_category_image-1.png&amp;w=1080&amp;q=75 1080w, /_next/image?url=https%3A%2F%2Fsandbox-api.stagingapps.net%2Fimages%2Fcategory%2F011223-134706_category_image-1.png&amp;w=1200&amp;q=75 1200w, /_next/image?url=https%3A%2F%2Fsandbox-api.stagingapps.net%2Fimages%2Fcategory%2F011223-134706_category_image-1.png&amp;w=1920&amp;q=75 1920w, /_next/image?url=https%3A%2F%2Fsandbox-api.stagingapps.net%2Fimages%2Fcategory%2F011223-134706_category_image-1.png&amp;w=2048&amp;q=75 2048w, /_next/image?url=https%3A%2F%2Fsandbox-api.stagingapps.net%2Fimages%2Fcategory%2F011223-134706_category_image-1.png&amp;w=3840&amp;q=75 3840w</value>
      <webElementGuid>e7959de1-5188-4c65-a910-864b9601a0d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=https%3A%2F%2Fsandbox-api.stagingapps.net%2Fimages%2Fcategory%2F011223-134706_category_image-1.png&amp;w=3840&amp;q=75</value>
      <webElementGuid>e3778b62-f070-41aa-99ea-dd18239147c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_96f5ea max-w-md mx-auto min-w-[320px]&quot;]/main[1]/div[@class=&quot;flex flex-col gap-5 px-4 py-0&quot;]/div[@class=&quot;text-black&quot;]/div[@class=&quot;mx-auto max-w-screen-xl&quot;]/div[@class=&quot;w-full grid grid-cols-4 gap-y-3 gap-x-3 items-start&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;w-full rounded-lg overflow-hidden group justify-center items-center bg-[#F2EEEE] cursor-pointer&quot;]/img[1]</value>
      <webElementGuid>1b8db199-edad-4f09-93d3-f70452176353</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/img</value>
      <webElementGuid>2d35566a-f546-4d24-8e9a-3a563448837b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_next/image?url=https%3A%2F%2Fsandbox-api.stagingapps.net%2Fimages%2Fcategory%2F011223-134706_category_image-1.png&amp;w=3840&amp;q=75']</value>
      <webElementGuid>520aeeeb-78e1-4146-b042-c06ff8dba021</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
