<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>decrease button</name>
   <tag></tag>
   <elementGuidId>d00052c4-b028-4387-b77c-4aecdf89483e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.cursor-pointer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>img >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>57c9ebb0-5529-4491-adce-1e8e233f1a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>df76548b-6ddf-412e-a318-08ce9b6e9db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>35365bc0-fb96-4a12-a611-d68998b547f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>2af49cfc-5ae1-44bf-b622-6a22ac8c22ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>8ab43fa6-8ef7-44ad-8446-31fcf75e8cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>efd2f6a9-1c4d-4660-ad36-77ebf82d2cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer</value>
      <webElementGuid>b73b77d1-98a4-46de-b37b-1da809fbcc93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/MinusCircleActive.svg</value>
      <webElementGuid>429d3640-4cb7-43c8-9a9a-ae51ae31cbce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_96f5ea max-w-md mx-auto min-w-[320px]&quot;]/div[@class=&quot;m-5&quot;]/section[@class=&quot;text-black pb-10&quot;]/div[@class=&quot;flex flex-col gap-3&quot;]/div[@class=&quot;w-full border-b pb-3&quot;]/div[@class=&quot;flex flex-row gap-3&quot;]/div[@class=&quot;w-3/4&quot;]/div[@class=&quot;w-full  flex flex-col justify-center&quot;]/div[@class=&quot;flex items-center space-x-4 justify-between&quot;]/div[@class=&quot;flex items-center justify-center gap-1&quot;]/img[@class=&quot;cursor-pointer&quot;]</value>
      <webElementGuid>49068f69-7ac0-4441-966d-edd9ecc1f108</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>5103a5ed-d0be-4c3f-ba92-d82ceb495782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/MinusCircleActive.svg']</value>
      <webElementGuid>3d99bae3-f9d9-4afd-8052-33794b9b3db9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
