<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>notes</name>
   <tag></tag>
   <elementGuidId>0e3714eb-0caf-4c32-b5d5-387b20c50d3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-notes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-notes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Tambah catatan untuk pesanan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c6d8215b-7a96-4261-b273-722459ccecc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-notes</value>
      <webElementGuid>1b2360fc-846b-472e-8df3-2b50f7df58d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>94c2b845-496d-4c51-9633-838a420687ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full p-4 pl-3 text-sm text-gray-900 border border-gray-300 rounded-lg  focus:ring-blue-500 focus:border-blue-500 dark:border-gray-600 dark:placeholder-gray-400 dark:focus:ring-blue-500 dark:focus:border-blue-500</value>
      <webElementGuid>66fae3c9-d53d-4a0c-a317-7b2ab68306f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tambah catatan untuk pesanan</value>
      <webElementGuid>a77ed36e-6661-4675-87f2-30bf0c1de3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5bd68b2c-81bb-45c8-8a63-dea2d656b183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-notes&quot;)</value>
      <webElementGuid>3dd70a8e-02aa-4c7f-9055-811ba632d51e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-notes']</value>
      <webElementGuid>66deaf39-d1c7-4a33-a1d8-7104137c7832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>f0456c4e-2cb4-419e-a4c9-385327bc2eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field-notes' and @placeholder = 'Tambah catatan untuk pesanan' and @type = 'text']</value>
      <webElementGuid>55110de4-8ff8-48d8-9dbf-d2d51796c90d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
